"use client";
import { ReactNode } from 'react'
import { SessionProvider } from 'next-auth/react';

import './globals.css'

interface IProps { children: ReactNode, session: any }

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }: IProps) {
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <div>{children}</div>
        </SessionProvider>        
      </body>
    </html>
  )
}
